theme: minima
title: Tutoring with Kalila
author: Kalila Chand
email: kalilatutor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Please get in touch for personal online tuition for students up to GCSE level.

# social links
instagram_username: kalilastudenttutor
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  calilak # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
